# Generated by Django 6.0.4 on 2026-04-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='instasend_tracking_id',
            new_name='intasend_tracking_id',
        ),
    ]
